(in-package :com.alibaba.fastjson.parser)

(use-package :defenum)

(defenum (Feature)
    ((AutoCloseSource)
     (AllowComment)
     (AllowUnQuotedFieldNames)
     (AllowSingleQuotes)
     (InternFieldNames)
     (AllowISO8601DateFormat)
     (AllowArbitraryCommas)
     (UseBigDecimal)
     (IgnoreNotMatch)
     (SortFeidFastMatch)
     (DisableASM)
     (DisableCircularReferenceDetect)
     (InitStringFieldAsEmpty)
     (SupportArrayToBean)
     (OrderedField)
     (DisableSpecialKeyDetect)
     (UseObjectArray)
     (SupportNonPublicField)
     (IgnoreAutoType)
     (DisableFieldSmartMatch)
     (SupportAutoType)
     (NonStringKeyAsString)
     (CustomMapDeserializer)
     (ErrorOnEnumNotMatch)
     (SafeMode)
     (TrimStringFieldValue)
     (UseNativeJavaObject))
    ((mask))
    (:initialize (format t "initialize...~%")))
