(in-package :rd-cost.web)

(defclass LoginUser ()
  ((token :type string :initform "")
   (loginTime :initform nil)
   (expireTime :initform nil)
   (ipaddr :initform nil)
   (loginLocation :initform nil)
   (browser :initform nil)
   (os :initform nil)
   (user :type SysUser :initarg :user)
   (permissions :initarg :permissions)))
